#pragma once
namespace Colonization
{
extern char *COLONIZATION_CORE_CATEGORY;
extern char *COLONIZATION_SERVER_ONLY_CATEGORY;
extern char *COLONIZATION_SHARED_CATEGORY;
extern char *COLONIZATION_CLIENT_ONLY_CATEGORY;
}
